add publish step

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,7 +1,10 @@
-name: "Publish Linux to Nuget"
+name: "Publish to Nuget"
 
 on:
   workflow_dispatch 
+permissions:
+  packages: write
+  contents: read
 jobs:
   get_version_numbers:
     runs-on: ubuntu-latest
@@ -13,30 +16,71 @@ jobs:
       - name: Get Cmpnnt.Pia.Ctl Version
         id: get-ctl-version
         env:
-          regex: '##\s\[([0-9\.]+)\]\s-\s[0-9]{4}-[0-9]{2}-[0-9]{2}'
-        run: echo version=$(sed -nr "s/$regex/\1/p" Cmpnnt.Pia.Ctl/Changelog.md | head -n1) >> $GITHUB_OUTPUT
+          regex: '##\s\[v([0-9\.]+)\]\s-\s[0-9]{4}-[0-9]{2}-[0-9]{2}'
+        run: echo version=$(sed -nr "s/$regex/\1/p" Cmpnnt.Pia.Ctl/CHANGELOG.md | head -n1) >> $GITHUB_OUTPUT
+      - name: Check ctl version number
+        if: steps.get-ctl-version.outputs == ''
+        run: echo "error parsing version number from ctl changelog"; exit 1
       - name: Get Cmpnnt.Pia.DependencyInjection Version
         id: get-di-version
         env:
-          regex: '##\s\[([0-9\.]+)\]\s-\s[0-9]{4}-[0-9]{2}-[0-9]{2}'
-        run: echo version=$(sed -nr "s/$regex/\1/p" Cmpnnt.Pia.DependencyInjection/Changelog.md | head -n1) >> $GITHUB_OUTPUT
-  add_nuget_source:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Add Github Nuget Source
-        id: add-github-nuget-source
-        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cmpnnt/index.json"
-  package_linux:
-    runs-on: ubuntu-latest
+          regex: '##\s\[v([0-9\.]+)\]\s-\s[0-9]{4}-[0-9]{2}-[0-9]{2}'
+        run: echo version=$(sed -nr "s/$regex/\1/p" Cmpnnt.Pia.DependencyInjection/CHANGELOG.md | head -n1) >> $GITHUB_OUTPUT
+      - name: Check di version number
+        if: steps.get-di-version.outputs == ''
+        run: echo "error parsing version number from ctl changelog"; exit 1
+  ensure_packages: # on PRs
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
     needs: get_version_numbers
+    if: ${{ !github.event.pull_request.merged }}
     steps:
       - uses: actions/checkout@v4
-      - name: Create Package for Linux
-        id: create-package-linux
-        run: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get-ctl-version-number.outputs.ctl-version-number }} Cmpnnt.Pia.Ctl/Cmpnnt.Pia.Ctl.csproj
-  #TODO: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get-ctl-version-number.outputs.ctl-version-number }}
-  # and remove the `version` property from the .csproj files. The version number should come only from the changelog
-  # package on PR to verify but only push the package on main
-  
-  
-# TODO: Consider other fail fast items and CI job order and dependencies
+      - name: Create Ctl Package
+        id: create-ctl-package
+        run: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get_version_numbers.outputs.ctl-version-number }} Cmpnnt.Pia.Ctl/Cmpnnt.Pia.Ctl.csproj
+      - name: Create DI Package
+        id: create-di-package
+        run: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get_version_numbers.outputs.di-version-number }} Cmpnnt.Pia.DependencyInjection/Cmpnnt.Pia.DependencyInjection.csproj
+  publish_ctl_package: # on merge to main
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+    needs: get_version_numbers
+    if: ${{ github.event.pull_request.merged }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Add Github Nuget Source
+        id: add-github-nuget-source
+        run: dotnet nuget add source --username cmpnnt --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cmpnnt/index.json"
+      - name: Create Ctl Package
+        id: create-ctl-package
+        run: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get_version_numbers.outputs.ctl-version-number }} Cmpnnt.Pia.Ctl/Cmpnnt.Pia.Ctl.csproj
+      - name: Push Ctl Package to Nuget
+        id: push-ctl-package
+        run: dotnet nuget push 'Cmpnnt.Pia.Ctl/bin/Release/Cmpnnt.Pia.Ctl.${{ runner.os }}.${{ needs.get_version_numbers.outputs.ctl-version-number }}.nupkg' --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
+  publish_di_package: # on merge to main
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+    needs: get_version_numbers
+    if: ${{ github.event.pull_request.merged }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Add Github Nuget Source
+        id: add-github-nuget-source
+        run: dotnet nuget add source --username cmpnnt --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cmpnnt/index.json"
+      - name: Create DI Package
+        id: create-di-package
+        run: dotnet pack -c Release --nologo -p:PackageVersion=${{ needs.get_version_numbers.outputs.di-version-number }} Cmpnnt.Pia.DependencyInjection/Cmpnnt.Pia.DependencyInjection.csproj
+      - name: Push DI Package to Nuget
+        id: push-di-package
+        run: dotnet nuget push 'Cmpnnt.Pia.DependencyInjection/bin/Release/Cmpnnt.Pia.DependencyInjection.${{ runner.os }}.${{ needs.get_version_numbers.outputs.di-version-number }}.nupkg' --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
+        
+# TODO: Figure out how to conditionally compile and publish packages based on whether their changelog has changed.
+# TODO: remove github nuget sources and replace with nuget.org
+# TODO: change workflow triggers. PR/Merge should trigger changelog. Changelog should trigger both documentation and publish workflows
